_wandb:
    value:
        cli_version: 0.28.2
        e:
            a5px06o66w9hoibe4pkli4uyay29kw6s:
                args:
                    - --config
                    - config/toy-clip.json
                codePath: clip/train.py
                codePathLocal: train.py
                cpu_count: 20
                cpu_count_logical: 40
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "234039422976"
                        used: "87937941504"
                email: sian.shinjo@students.iiit.ac.in
                executable: /home2/sian/summer-project/vision_transformer/.venv/bin/python
                git:
                    commit: 5fb17d854bbf281457ad7797a736afe176243648
                    remote: git@github.com:noss123/summer-project.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-92993a3c-34fd-4632-a395-c0ceb342d49e
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-6d0923d1-acdd-0440-196d-09c6ddd043a9
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-fa6e4618-8db4-7571-0d0e-7b93d46964b2
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-d40081f2-3bcf-8216-d67c-a5be04f0408b
                host: gnode084
                memory:
                    total: "135025561600"
                os: Linux-5.15.0-187-generic-x86_64-with-glibc2.35
                program: /home2/sian/summer-project/clip/train.py
                python: CPython 3.10.12
                root: /home2/sian/summer-project/clip
                slurm:
                    cluster_name: ada
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "10"
                    cpus_per_task: "10"
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: sian
                    job_cpus_per_node: "10"
                    job_gid: "2002"
                    job_gpus: 0,1,2,3
                    job_id: "2690872"
                    job_name: clip
                    job_nodelist: gnode084
                    job_num_nodes: "1"
                    job_partition: u22
                    job_qos: normal
                    job_uid: "3980"
                    job_user: sian
                    jobid: "2690872"
                    localid: "0"
                    mem_per_cpu: "1536"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: gnode084
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home2/sian/summer-project/clip
                    submit_host: ada.iiit.ac.in
                    task_pid: "2195882"
                    tasks_per_node: "1"
                    topology_addr: gnode084
                    topology_addr_pattern: node
                    working_cluster: ada:172.16.0.2:6817:9728:109
                startedAt: "2026-09-07T15:34:59.673424Z"
                writerId: a5px06o66w9hoibe4pkli4uyay29kw6s
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
            "2":
                - 1
                - 11
                - 41
                - 49
            "3":
                - 16
            "4": 3.10.12
            "5": 0.28.2
            "6": 5.16.1
            "12": 0.28.2
            "13": linux-x86_64
annotations:
    value: ../data/Flickr8k/text/Flickr8k.token.txt
batch_size:
    value: 32
checkpoint_path:
    value: checkpoints/toy-clip.pt
datapath:
    value: ../data/Flickr8k/images/Flicker8k_Dataset
embed_dim:
    value: 256
epochs:
    value: 20
learning_rate:
    value: 0.0001
run:
    value: toy-clip
vit_pretrained_path:
    value: ../vision_transformer/checkpoints/vit-cutmix.pt
